ignore:
  # testing utility
  - "cmd/create"
  # has sufficient secondary coverage
  - "internal/audit/response.go"
  # telemetry configuration
  - "internal/observe/telemetry.go"
  # bootstrap only
  - "main.go"
