ignore:
  # testing utility
  - "cmd/create"
  - "internal/profile/profiletest"
  - "internal/testhelpers"
  # has sufficient secondary coverage
  - "internal/audit/response.go"
  # telemetry configuration
  - "internal/observe/telemetry.go"
  # bootstrap only
  - "main.go"

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: unit
      carryforward: true
    - name: integration
      carryforward: true
