#!/usr/bin/env bash

#
# executing this script from your infrastructure's environment agent hook will
# configure Github App Auth for every build
#
# Changing the parameters supplied will be necessary to ensure that agents can
# connect to the service and include the correct audience.
#
BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_CHINMINA_URL="http://chinmina-bridge" \
BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_AUDIENCE="github-app-auth:chinmina" \
BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_PROFILES="repo:default org:buildkite-plugin-testing" \
    source /buildkite/plugins/chinmina-git-credentials-buildkite-plugin/hooks/environment

# optional: it is possible to change the git URL, converting it from SSH to
# HTTPS if that is desired.
