#!/usr/bin/env bash

set -euo pipefail

#
# executing this script from your infrastructure's environment agent hook will
# configure Github App Auth for every build
#
# Changing the parameters supplied will be necessary to ensure that agents can
# connect to the service and include the correct audience.
#

# Setup a temporary directory for this job

TMPDIR=$(mktemp -d)
export TMPDIR
echo "Using temp dir: ${TMPDIR}"

BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_CHINMINA_URL="http://chinmina-bridge" \
BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_AUDIENCE="github-app-auth:chinmina" \
BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_PROFILES_0="repo:default" \
BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_PROFILES_1="org:buildkite-plugin-testing" \
    source /buildkite/plugins/chinmina-git-credentials-buildkite-plugin/hooks/environment

# References the local instance of chinmina service
BUILDKITE_PLUGIN_CHINMINA_TOKEN_CHINMINA_URL="http://chinmina-bridge" \
BUILDKITE_PLUGIN_CHINMINA_TOKEN_AUDIENCE="github-app-auth:chinmina" \
    source /buildkite/plugins/chinmina-token-buildkite-plugin/hooks/environment

# optional: it is possible to change the git URL, converting it from SSH to
# HTTPS if that is desired.
