#!/usr/bin/env bash

echo "installing Github credential plugin"

plugin_repo="https://github.com/chinmina/chinmina-git-credentials-buildkite-plugin.git"
plugin_version="feat/support-profiles" # TODO: use a release tag once plugin is finalised
plugin_dir="/buildkite/plugins/chinmina-git-credentials-buildkite-plugin"

[[ -d "${plugin_dir}" ]] && rm -rf "${plugin_dir}"

GIT_CONFIG_COUNT=1 \
GIT_CONFIG_KEY_0=advice.detachedHead \
GIT_CONFIG_VALUE_0=false \
  git clone --depth 1 --single-branch --no-tags \
    --branch "${plugin_version}" -- \
    "${plugin_repo}" "${plugin_dir}"
