#!/usr/bin/env bash

echo "installing Github credential plugin"

plugin_repo="https://github.com/chinmina/chinmina-git-credentials-buildkite-plugin.git"
plugin_version="v1.2.0"
plugin_dir="/buildkite/plugins/chinmina-git-credentials-buildkite-plugin"

[[ -d "${plugin_dir}" ]] && rm -rf "${plugin_dir}"

GIT_CONFIG_COUNT=1 \
GIT_CONFIG_KEY_0=advice.detachedHead \
GIT_CONFIG_VALUE_0=false \
  git clone --depth 1 --single-branch --no-tags \
    --branch "${plugin_version}" -- \
    "${plugin_repo}" "${plugin_dir}"

echo "installing Chinmina token library plugin"

plugin_repo="https://github.com/chinmina/chinmina-token-buildkite-plugin.git"
plugin_version="v1.0.1"
plugin_dir="/buildkite/plugins/chinmina-token-buildkite-plugin"

[[ -d "${plugin_dir}" ]] && rm -rf "${plugin_dir}"

GIT_CONFIG_COUNT=1 \
GIT_CONFIG_KEY_0=advice.detachedHead \
GIT_CONFIG_VALUE_0=false \
  git clone --depth 1 --single-branch --no-tags \
    --branch "${plugin_version}" -- \
    "${plugin_repo}" "${plugin_dir}"

# Installing gh cli
echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
apk add github-cli@community
